name: Docker Sample
on: push

jobs:
  build:
    name: Docker Sample
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
      - name: node version
        run: node --version
      - name: node -e 
        run: node -e 'console.log("Docker Sample");'
